/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://o7evcg7lrbfbfn7dodujskkruu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rrww5isp35hkxavgy3axpytmve",
    "aws_cognito_identity_pool_id": "us-east-1:7093b938-7374-440a-b8ca-4b9a6c0d6cda",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_epal8yjKC",
    "aws_user_pools_web_client_id": "5tak9tsccfsb6ptnf2507f0ujo",
    "oauth": {}
};


export default awsmobile;
